# Generated by Django 2.2.6 on 2020-01-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200103_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, help_text='Your name', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='nickname',
            field=models.CharField(blank=True, help_text='Your nickname', max_length=120, null=True),
        ),
    ]
