# Generated by Django 2.2.6 on 2019-12-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingprofile_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='customer_id',
            new_name='paypal_customer_id',
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
