# Generated by Django 2.2.6 on 2020-01-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='paypal_customer_id',
            new_name='paypal_CreditCard_id',
        ),
    ]
