# Generated by Django 2.2.6 on 2020-01-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20200103_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='paypal_BillingAgreementToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
