# Generated by Django 2.2.6 on 2020-01-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billingprofile_paypal_billingagreementtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='last4',
            new_name='number',
        ),
    ]
