# Generated by Django 2.2.6 on 2020-01-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_billingprofile_braintree_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='testfield',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
