# Generated by Django 2.2.6 on 2020-01-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20200115_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='testfield',
            new_name='postal_code',
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
