# Generated by Django 2.2.6 on 2020-01-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_auto_20200115_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='braintree_payment_method_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
