# Generated by Django 2.2.6 on 2020-01-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_billingprofile_braintree_payment_method_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='braintree_cardholder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='braintree_expiration_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='braintree_masked_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
