# Generated by Django 2.2.6 on 2020-01-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
