# Generated by Django 2.2.6 on 2020-01-20 04:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_billingprofile_braintree_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='braintree_subscriptions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), default=list, size=None),
        ),
    ]
