# Generated by Django 2.2.6 on 2020-01-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_auto_20200120_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='refunded',
            new_name='is_canceled',
        ),
    ]
