# Generated by Django 2.2.6 on 2020-01-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_auto_20200120_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='stripe_customer_id',
        ),
    ]
