# Generated by Django 2.2.6 on 2020-02-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webharvest', '0002_webharvestmessagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebharvestRobot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
