# Generated by Django 2.2.6 on 2020-02-11 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webharvest', '0003_webharvestrobot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webharvestthread',
            name='first',
        ),
        migrations.RemoveField(
            model_name='webharvestthread',
            name='second',
        ),
        migrations.AddField(
            model_name='webharvestthread',
            name='human',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webharvest_chat_thread_human', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webharvestthread',
            name='robot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webharvest_chat_thread_robot', to='webharvest.WebharvestRobot'),
        ),
    ]
