# Generated by Django 2.2.6 on 2020-02-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webharvest', '0004_auto_20200211_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webharvestchatmessage',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sender'),
        ),
    ]
