# Generated by Django 2.2.6 on 2020-02-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webharvest', '0005_auto_20200211_0215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebharvestMessageModel',
        ),
    ]
