# Generated by Django 2.2.6 on 2020-02-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webharvest', '0007_webharvestjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='webharvestjob',
            name='search_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
