# Generated by Django 2.2.6 on 2020-03-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webharvest', '0008_webharvestjob_search_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='webharvestthread',
            name='message_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
