# Generated by Django 2.2.6 on 2020-04-07 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webharvest', '0010_webharvestspreadsheet_webharvestspreadsheetrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='webharvestthread',
            name='spreadsheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webharvest_chat_thread_spreadsheet', to='webharvest.WebharvestSpreadSheet'),
        ),
    ]
