# Generated by Django 2.2.6 on 2020-04-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webharvest', '0011_webharvestthread_spreadsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='webharvestspreadsheet',
            name='first_row',
            field=models.TextField(blank=True, null=True),
        ),
    ]
