# Generated by Django 2.2.6 on 2019-12-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='ip_address',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
