# Generated by Django 2.2.6 on 2020-01-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_digital',
            field=models.BooleanField(default=True),
        ),
    ]
