# Generated by Django 2.2.6 on 2019-11-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20191101_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='subscription/'),
        ),
    ]
