# Generated by Django 2.2.6 on 2020-01-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='braintree_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
