# Generated by Django 2.2.6 on 2020-01-21 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription_braintree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='braintree_id',
        ),
    ]
