# Generated by Django 2.2.6 on 2019-11-04 06:08

from django.db import migrations, models
import subscription.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=subscription.models.upload_image_path),
        ),
    ]
