# Generated by Django 2.2.6 on 2019-11-19 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='subscription',
            new_name='subscriptions',
        ),
    ]
