# Generated by Django 2.2.6 on 2020-02-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='channel_name',
        ),
        migrations.AddField(
            model_name='user',
            name='bool_webharvest_chat_active',
            field=models.BooleanField(default=False),
        ),
    ]
