# Generated by Django 2.2.6 on 2020-02-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200217_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bool_webharvest_robot_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='webharvest_robot_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
