# Generated by Django 2.2.6 on 2020-03-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200217_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bool_temporary_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='temporary_user_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
