# Generated by Django 2.2.6 on 2019-12-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('orders', '0002_auto_20191127_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='billing_address', to='addresses.Address'),
        ),
    ]
