# Generated by Django 2.2.6 on 2020-01-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_subscriptionpurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionpurchase',
            old_name='refunded',
            new_name='is_canceled',
        ),
    ]
