# Generated by Django 2.2.6 on 2020-01-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200120_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpurchase',
            name='braintree_subscription_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpurchase',
            name='is_canceled_final_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpurchase',
            name='is_canceled_initial_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
